services:
  postgres:
    image: postgres:15-alpine
    container_name: dhanam-postgres
    environment:
      POSTGRES_USER: dhanam
      POSTGRES_PASSWORD: localdev
      POSTGRES_DB: dhanam
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - dhanam_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhanam"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dhanam-redis
    ports:
      - "6379:6379"
    volumes:
      - dhanam_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: dhanam-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    
  localstack:
    image: localstack/localstack:latest
    container_name: dhanam-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,kms
      - DEBUG=0
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - dhanam_localstack_data:/tmp/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: dhanam-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dhanam-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  dhanam_postgres_data:
  dhanam_redis_data:
  dhanam_localstack_data:

networks:
  default:
    name: dhanam-network
