version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: dhanam-postgres-test
    environment:
      POSTGRES_DB: dhanam_test
      POSTGRES_USER: dhanam_test
      POSTGRES_PASSWORD: test_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dhanam_test -d dhanam_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    container_name: dhanam-redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog-test:
    image: mailhog/mailhog:latest
    container_name: dhanam-mailhog-test
    ports:
      - "1026:1025" # SMTP
      - "8026:8025" # Web UI
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_test_data:
  redis_test_data:

networks:
  default:
    name: dhanam-test-network