apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- api-deployment.yaml
- admin-deployment.yaml
- web-deployment.yaml
- network-policies.yaml
- pdb.yaml

# Image transformer: maps short names to full GHCR paths
# CI workflows update these entries with @sha256:... digests after each build
images:
- digest: sha256:299a8c030eea02eaa08543013fafc970b6991f7596e4ba192c595679c0a59795
  name: dhanam-admin
  newName: ghcr.io/madfam-org/dhanam/admin
- digest: sha256:50255693332a084e6a2b45df87b791183f5d676d07f00f247e83202ff9e33678
  name: dhanam-api
  newName: ghcr.io/madfam-org/dhanam/api
- digest: sha256:a44e909efed49b5ebe95fdb637d726c922081fd15420f3d396ff1f28bd289b28
  name: dhanam-web
  newName: ghcr.io/madfam-org/dhanam/web
