apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- api-deployment.yaml
- admin-deployment.yaml
- web-deployment.yaml
- network-policies.yaml
- pdb.yaml

# Image transformer: maps short names to full GHCR paths
# CI workflows update these entries with @sha256:... digests after each build
images:
- digest: sha256:fc9b5eb9d0ac056a950503b73c7359192ca7a2fe3665d7e9ccd4a35197360a11
  name: dhanam-admin
  newName: ghcr.io/madfam-org/dhanam/admin
- digest: sha256:99f148de658c97258d2bd6756b246bc2a8a7cfb035d50028919cfc6bd88df95d
  name: dhanam-api
  newName: ghcr.io/madfam-org/dhanam/api
- digest: sha256:ee72df58b6f0ad70a63dc6bac73371f3570503e0c244f40314edd0dad57dedfa
  name: dhanam-web
  newName: ghcr.io/madfam-org/dhanam/web
