apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- api-deployment.yaml
- admin-deployment.yaml
- web-deployment.yaml
- network-policies.yaml
- pdb.yaml

# Image transformer: maps short names to full GHCR paths
# CI workflows update these entries with @sha256:... digests after each build
images:
- digest: sha256:c235b1cb2b329cdbf317e709d08056615c2f5a35ceaed5f34dfded9c3589eb1b
  name: dhanam-admin
  newName: ghcr.io/madfam-org/dhanam/admin
- digest: sha256:b97c5d5df83a054011ae7f3e6c73bcd4b1735713d15d551529dca7d9146ebd6a
  name: dhanam-api
  newName: ghcr.io/madfam-org/dhanam/api
- digest: sha256:a44e909efed49b5ebe95fdb637d726c922081fd15420f3d396ff1f28bd289b28
  name: dhanam-web
  newName: ghcr.io/madfam-org/dhanam/web
