apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-monitors.yaml
  - prometheus-rules.yaml
  - alertmanager-config.yaml
  - grafana-dashboards-configmap.yaml
  - synthetic-cronjob.yaml
